# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Kadai19-MVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Kadai19-MVVM

pod'SwiftLint'
pod'RxSwift'
pod'RxCocoa'
end
